version 0.5.5

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -30,13 +30,26 @@ then
   echo "NANONEXT_SYS flag set"
   echo "Using 'libnng' and 'libmbedtls' installed in '/usr/local' ..."
   PKG_CFLAGS="-I/usr/local/include $PKG_CFLAGS"
-  PKG_LIBS="-L/usr/local/lib $PKG_LIBS"
+  if [ -d "/usr/local/lib64" ]
+  then
+    PKG_LIBS="-L/usr/local/lib64 $PKG_LIBS"
+  fi
+  if [ -d "/usr/local/lib" ]
+  then
+    PKG_LIBS="-L/usr/local/lib $PKG_LIBS"
+  fi
 else
-  echo "Detecting cmake..."
+  echo "Detecting 'cmake'..."
   which cmake
   if [ $? -ne 0 ]
   then
     export PATH=$PATH:/Applications/CMake.app/Contents/bin
+    which cmake
+    if [ $? -ne 0 ]
+    then
+      echo "'cmake' is required but is not found"
+      exit 1
+    fi
   fi
   echo "Downloading 'libmbedtls' source..."
   curl -sL https://api.github.com/repos/Mbed-TLS/mbedtls/tarball/$TLS_VER -o mbedtls.tar.gz
@@ -50,7 +63,8 @@ else
   mkdir build
   cd build
   echo "Compiling 'libmbedtls' from source..."
-  cmake -DCMAKE_POSITION_INDEPENDENT_CODE=1 -DENABLE_TESTING=0 -DENABLE_PROGRAMS=0 -DCMAKE_INSTALL_PREFIX=../../temp -DCMAKE_INSTALL_MESSAGE=NEVER ..
+  cmake -DCMAKE_POSITION_INDEPENDENT_CODE=1 -DENABLE_TESTING=0 -DENABLE_PROGRAMS=0 \
+    -DCMAKE_INSTALL_PREFIX=../../temp -DCMAKE_INSTALL_MESSAGE=NEVER ..
   cmake --build .
   cmake --install .
   cd ../..
@@ -59,13 +73,22 @@ else
   mkdir build
   cd build
   echo "Compiling 'libnng' from source..."
-  cmake -DCMAKE_POSITION_INDEPENDENT_CODE=1 -DNNG_ENABLE_TLS=1 -DNNG_ELIDE_DEPRECATED=1 -DNNG_TESTS=0 -DNNG_TOOLS=0 -DCMAKE_INSTALL_PREFIX=../../temp -DCMAKE_INSTALL_MESSAGE=NEVER ..
+  cmake -DCMAKE_POSITION_INDEPENDENT_CODE=1 -DNNG_ENABLE_TLS=1 \
+    -DNNG_ELIDE_DEPRECATED=1 -DNNG_TESTS=0 -DNNG_TOOLS=0 \
+    -DCMAKE_INSTALL_PREFIX=../../temp -DCMAKE_INSTALL_MESSAGE=NEVER ..
   cmake --build .
   cmake --install .
   cd ../..
   rm -rf nanomsg-nng-$LIB_VER
   PKG_CFLAGS="-I`pwd`/temp/include $PKG_CFLAGS"
-  PKG_LIBS="-L`pwd`/temp/lib $PKG_LIBS"
+  if [ -d "temp/lib64" ]
+  then
+    PKG_LIBS="-L`pwd`/temp/lib64 $PKG_LIBS"
+  fi
+  if [ -d "temp/lib" ]
+  then
+    PKG_LIBS="-L`pwd`/temp/lib $PKG_LIBS"
+  fi
 fi
 
 # Write to Makevars
