version 0.6.0

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -7,6 +7,8 @@ TLS_VER="869298b"
 # Initialise
 PKG_CFLAGS=""
 PKG_LIBS="-lnng -lmbedtls -lmbedx509 -lmbedcrypto"
+NNG_CFLAGS=""
+NNG_LIBS=""
 
 # Find compiler
 CC=`${R_HOME}/bin/R CMD config CC`
@@ -17,28 +19,48 @@ echo "#include <stdint.h>
 uint64_t v;
 int main() {
     return (int)__atomic_load_n(&v, __ATOMIC_ACQUIRE);
-}" | ${CC} -x c - -o /dev/null > /dev/null 2>&1
+}" | ${CC} -xc - -o /dev/null > /dev/null 2>&1
 if [ $? -ne 0 ]
 then
-  echo "Adding -latomic linker flag"
+  echo "Adding -latomic linker flag ..."
   PKG_LIBS="$PKG_LIBS -latomic"
 fi
 
-# Use system lib or download and compile from source (default)
-if [ "$NANONEXT_SYS" ]
+# Find MbedTLS and compile if necessary
+if [ "$INCLUDE_DIR" ] || [ "$LIB_DIR" ]
 then
-  echo "NANONEXT_SYS flag set"
-  echo "Using 'libnng' and 'libmbedtls' installed in '/usr/local' ..."
+  PKG_CFLAGS="-I$INCLUDE_DIR $PKG_CFLAGS"
+  PKG_LIBS="-L$LIB_DIR $PKG_LIBS"
+  echo "Found INCLUDE_DIR $INCLUDE_DIR"
+  echo "Found LIB_DIR $LIB_DIR"
+elif [ -d "/usr/local/include/mbedtls" ]
+then
   PKG_CFLAGS="-I/usr/local/include $PKG_CFLAGS"
-  if [ -d "/usr/local/lib64" ]
-  then
-    PKG_LIBS="-L/usr/local/lib64 $PKG_LIBS"
-  fi
-  if [ -d "/usr/local/lib" ]
-  then
-    PKG_LIBS="-L/usr/local/lib $PKG_LIBS"
-  fi
-else
+  PKG_LIBS="-L/usr/local/lib $PKG_LIBS"
+  echo "Found 'libmbedtls' $PKG_CFLAGS"
+elif [ -d "/usr/include/mbedtls" ]
+then
+  PKG_CFLAGS="-I/usr/include $PKG_CFLAGS"
+  PKG_LIBS="-L/usr/lib $PKG_LIBS"
+  echo "Found 'libmbedtls' $PKG_CFLAGS"
+elif [ -d "/usr/local/opt/mbedtls" ]
+then
+  PKG_CFLAGS="-I/usr/local/opt/mbedtls/include $PKG_CFLAGS"
+  PKG_LIBS="-L/usr/local/opt/mbedtls/lib $PKG_LIBS"
+  echo "Found 'libmbedtls' $PKG_CFLAGS"
+fi
+
+echo "#include <mbedtls/version.h>
+int main() {
+#if MBEDTLS_VERSION_MAJOR >= 2
+      return 0;
+#else
+      error;
+#endif
+}" | ${CC} ${PKG_CFLAGS} -xc - -o /dev/null > /dev/null 2>&1
+if [ $? -ne 0 ]
+then
+  echo "No existing 'libmbedtls' >= 2 found"
   echo "Detecting 'cmake'..."
   which cmake
   if [ $? -ne 0 ]
@@ -47,48 +69,106 @@ else
     which cmake
     if [ $? -ne 0 ]
     then
-      echo "'cmake' is required but is not found"
+      echo "Required 'cmake' not found"
       exit 1
     fi
   fi
-  echo "Downloading 'libmbedtls' source..."
-  curl -sL https://api.github.com/repos/Mbed-TLS/mbedtls/tarball/$TLS_VER -o mbedtls.tar.gz
-  gzip -dc mbedtls.tar.gz | tar -xf -
-  rm -f mbedtls.tar.gz
-  echo "Downloading 'libnng' source..."
-  curl -sL https://api.github.com/repos/nanomsg/nng/tarball/$LIB_VER -o nng.tar.gz
-  gzip -dc nng.tar.gz | tar -xf -
-  rm -f nng.tar.gz
-  cd Mbed-TLS-mbedtls-$TLS_VER
-  mkdir build
-  cd build
-  echo "Compiling 'libmbedtls' from source..."
-  cmake -DCMAKE_POSITION_INDEPENDENT_CODE=1 -DENABLE_TESTING=0 -DENABLE_PROGRAMS=0 \
-    -DCMAKE_INSTALL_PREFIX=../../temp -DCMAKE_INSTALL_MESSAGE=NEVER ..
+  echo "Detecting 'xz'..."
+  which xz
+  if [ $? -ne 0 ]
+  then
+    tar -xf inst/mbedtls-$TLS_VER.tar.xz
+    if [ $? -ne 0 ]
+    then
+      echo "No 'xz' command found"
+      exit 1
+    fi
+  else
+    xz -dc inst/mbedtls-$TLS_VER.tar.xz | tar -xf -
+  fi
+  cd mbedtls-$TLS_VER
+  echo "Compiling 'libmbedtls' from source ..."
+  cmake -DCMAKE_INSTALL_PREFIX=../install .
   cmake --build .
   cmake --install .
-  cd ../..
-  rm -rf Mbed-TLS-mbedtls-$TLS_VER
-  cd nanomsg-nng-$LIB_VER
-  mkdir build
-  cd build
-  echo "Compiling 'libnng' from source..."
-  cmake -DCMAKE_POSITION_INDEPENDENT_CODE=1 -DNNG_ENABLE_TLS=1 \
-    -DNNG_ELIDE_DEPRECATED=1 -DNNG_TESTS=0 -DNNG_TOOLS=0 \
-    -DCMAKE_INSTALL_PREFIX=../../temp -DCMAKE_INSTALL_MESSAGE=NEVER ..
+  cd ..
+  rm -rf mbedtls-$TLS_VER
+fi
+
+# Find NNG and compile if necessary
+if [ "$INCLUDE_DIR" ] || [ "$LIB_DIR" ]
+then
+  NNG_CFLAGS="-I$INCLUDE_DIR"
+  NNG_LIBS="-L$LIB_DIR"
+elif [ -d "/usr/local/include/nng" ]
+then
+  NNG_CFLAGS="-I/usr/local/include"
+  NNG_LIBS="-L/usr/local/lib"
+elif [ -d "/usr/include/nng" ]
+then
+  NNG_CFLAGS="-I/usr/include"
+  NNG_LIBS="-L/usr/lib"
+elif [ -d "/usr/local/opt/nng" ]
+then
+  NNG_CFLAGS="-I/usr/local/opt/nng/include"
+  NNG_LIBS="-L/usr/local/opt/nng/lib"
+fi
+
+echo "#include <nng/nng.h>
+int main() {
+    bool test = nng_aio_busy;
+    return 0;
+}" | ${CC} ${NNG_CFLAGS} -xc - -o /dev/null > /dev/null 2>&1
+if [ $? -ne 0 ]
+then
+  echo "No existing 'libnng' >= 1.6.0 found"
+  echo "Detecting 'cmake'..."
+  which cmake
+  if [ $? -ne 0 ]
+  then
+    export PATH=$PATH:/Applications/CMake.app/Contents/bin
+    which cmake
+    if [ $? -ne 0 ]
+    then
+      echo "Required 'cmake' not found"
+      exit 1
+    fi
+  fi
+  echo "Detecting 'xz'..."
+  which xz
+  if [ $? -ne 0 ]
+  then
+    tar -xf inst/nng-$LIB_VER.tar.xz
+    if [ $? -ne 0 ]
+    then
+      echo "No 'xz' command found"
+      exit 1
+    fi
+  else
+    xz -dc inst/nng-$LIB_VER.tar.xz | tar -xf -
+  fi
+  cd nng-$LIB_VER
+  echo "Compiling 'libnng' from source ..."
+  cmake -DCMAKE_INSTALL_PREFIX=../install .
   cmake --build .
   cmake --install .
-  cd ../..
-  rm -rf nanomsg-nng-$LIB_VER
-  PKG_CFLAGS="-I`pwd`/temp/include $PKG_CFLAGS"
-  if [ -d "temp/lib64" ]
-  then
-    PKG_LIBS="-L`pwd`/temp/lib64 $PKG_LIBS"
-  fi
-  if [ -d "temp/lib" ]
-  then
-    PKG_LIBS="-L`pwd`/temp/lib $PKG_LIBS"
-  fi
+  cd ..
+  rm -rf nng-$LIB_VER
+else
+  echo "Found 'libnng' $NNG_CFLAGS"
+  PKG_CFLAGS="$NNG_CFLAGS $PKG_CFLAGS"
+  PKG_LIBS="$NNG_LIBS $PKG_LIBS"
+fi
+
+if [ -d "install/lib64" ]
+then
+  PKG_CFLAGS="-I../install/include $PKG_CFLAGS"
+  PKG_LIBS="-L../install/lib64 $PKG_LIBS"
+fi
+if [ -d "install/lib" ]
+then
+  PKG_CFLAGS="-I../install/include $PKG_CFLAGS"
+  PKG_LIBS="-L../install/lib $PKG_LIBS"
 fi
 
 # Write to Makevars
